[DRAFT] add REPO_SYNC to disable repo sync
lineageos4microg/docker-lineage-cicd pull request #432
Opened 2023-06-25 02:25 UTC by hellodword

related pr [#160](https://github.com/lineageos4microg/docker-lineage-cicd/pull/160/files) but less changes

2023-07-04 14:40 UTC, bananer requested changes
Documenting that option in the readme would be good.

Some local changes will still be lost, this might also be relevant for the documentation. See https://github.com/lineageos4microg/docker-lineage-cicd/blob/5c35c2e93cad4f5026e81a13f760fb15c854deee/src/build.sh#L159-L168

2023-08-07 10:47 UTC, petefoth commented
Assigned back to @hellodword for requested changes

Converted to 'Drafy'

2023-08-30 10:23 UTC, petefoth commented
Too many outstanding issues for this to be merged yet:
1. Documentation
2. Answer to @bananer's review question

2023-08-30 11:18 UTC, petefoth commented on Dockerfile
> +      python2 gcc-9 \
I think it would be clearer if we call the flag `SKIP-REPO_SYNC`, and invert the logic of the code in `build.sh` (and change the docs to match)

2023-08-30 11:50 UTC, petefoth commented on Dockerfile
> +      python2 gcc-9 \
Good questions. Too many open questions for this to get merged for Friday's build run. I'll set the PR back to Draft, and we can give it some more tghought in the next couple of weeks

2024-02-20 12:50 UTC, closed without merging